/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CacheStatsDto { 
    /**
     * Number of cats currently in the LRU cache. Oldest 2400 and newest 2400 are pinned (never evicted).
     */
    cats: number;
    /**
     * Max capacity of the cat LRU (dynamically adjusted between 5300 and 20000)
     */
    catsMax: number;
    /**
     * Number of txHash index entries (secondary lookup map)
     */
    txHashIndex: number;
    /**
     * Cached total cat count (maintained via auto-bump + sync notifications)
     */
    totalCatCount: number;
    /**
     * Cached last synced cat number. Defines the newest-pinned range: [n-2399 .. n].
     */
    lastSyncedCatNumber: number;
    /**
     * Cached Proof of Cat Work (sum of all mint fees in sats). Refreshed from DB after each sync cycle.
     */
    proofOfCatWork: number;
    /**
     * Detected container memory limit in MB (cgroup v2/v1, Node 20+ constrainedMemory, or fallback)
     */
    memoryLimitMB: number;
    /**
     * Target memory ceiling (75% of limit) in MB
     */
    memoryTargetMB: number;
    /**
     * Available memory before hitting target, in MB
     */
    memoryHeadroomMB: number;
    /**
     * Current resident memory (RSS) in MB
     */
    memoryRssMB: number;
    /**
     * Current V8 heap used in MB
     */
    memoryHeapUsedMB: number;
}

