/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatDto { 
    id: string;
    catNumber: number;
    txHash: string;
    blockHash: string;
    blockHeight: number;
    mintedAt: string;
    mintedBy?: string | null;
    fee: number;
    weight: number;
    size: number;
    feeRate: number;
    sat: number;
    value: number;
    category: string;
    genesis: boolean;
    catColors: Array<string>;
    male: boolean;
    female: boolean;
    designIndex: number;
    designPose: string;
    designExpression: string;
    designPattern: string;
    designFacing: string;
    laserEyes: string;
    background: string;
    backgroundColors: Array<string>;
    crown: string;
    glasses: string;
    glassesColors: Array<string>;
}

