/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatDto { 
    /**
     * Internal database ID (UUID)
     */
    id: string;
    /**
     * The incremented number of the cat. Cat #0 is the genesis cat.
     */
    catNumber: number;
    /**
     * Transaction hash (hex) where the CAT-21 ordinal was minted
     */
    txHash: string;
    /**
     * Block hash (hex) of the block containing the mint transaction
     */
    blockHash: string;
    /**
     * Block height where the CAT-21 ordinal was minted
     */
    blockHeight: number;
    /**
     * Timestamp when the cat was minted (ISO 8601)
     */
    mintedAt: string;
    /**
     * Address that received the first output of the mint transaction. Null for OP_RETURN outputs (cat is free).
     */
    mintedBy?: string | null;
    /**
     * Total fees paid to process the mint transaction (Unit: sats)
     */
    fee: number;
    /**
     * Weight of the mint transaction (Unit: WU — weight units)
     */
    weight: number;
    /**
     * Total size of the mint transaction (Unit: bytes)
     */
    size: number;
    /**
     * Fee rate paid to mint this cat (Unit: sat/vB). Determines the color of the cat.
     */
    feeRate: number;
    /**
     * The ordinal satoshi number associated with this cat
     */
    sat: number;
    /**
     * Value of the first output of the mint transaction (Unit: sats)
     */
    value: number;
    /**
     * Category based on cat number. sub1 holds the Genesis Cat only; the rest partition cats 1..999 999 by smallest-applicable band. Empty string is reserved for cats >= 1 000 000 (the TBD band).
     */
    category: CatDto.CategoryEnum;
    /**
     * Whether this is a genesis cat (white or black, probability 0.4%)
     */
    genesis: boolean;
    /**
     * All colors used to paint the cat (excluding laser eyes and other trait colors)
     */
    catColors: Array<string>;
    /**
     * Gender of the cat. Empty string for cats that have neither (rare edge case, e.g. some fixtures).
     */
    gender: CatDto.GenderEnum;
    /**
     * Design index (0-127), combination of pose, expression, pattern, and facing
     */
    designIndex: number;
    /**
     * Pose of the cat
     */
    designPose: CatDto.DesignPoseEnum;
    /**
     * Expression of the cat
     */
    designExpression: CatDto.DesignExpressionEnum;
    /**
     * Pattern of the cat
     */
    designPattern: CatDto.DesignPatternEnum;
    /**
     * Facing direction of the cat
     */
    designFacing: CatDto.DesignFacingEnum;
    /**
     * Laser eyes color (20% chance each), or None
     */
    laserEyes: CatDto.LaserEyesEnum;
    /**
     * Background type (25% chance each)
     */
    background: CatDto.BackgroundEnum;
    /**
     * Colors used to generate the background
     */
    backgroundColors: Array<string>;
    /**
     * Crown type (10% chance to have one)
     */
    crown: CatDto.CrownEnum;
    /**
     * Glasses type (10% chance each, 3D and Nouns only without laser eyes)
     */
    glasses: CatDto.GlassesEnum;
    /**
     * Colors used to paint the glasses (empty if no glasses)
     */
    glassesColors: Array<string>;
    /**
     * OpenRarity information-content score for this cat within its category band (raw Σ -log₂(p_i)). Higher = rarer. Each band is scored independently.
     */
    rarityBits?: number | null;
    /**
     * 1-based rarity rank within this cat\'s category. Strict total order — when two cats roll the same scored trait combination, the lower cat number wins the tie.
     */
    rarityRank?: number | null;
    /**
     * Total cats currently in this cat\'s category. For closed categories (sub1, sub1k, sub10k, etc.) this is the fixed drop size — `sub1` has size 1 (Genesis Cat only). For open categories it grows with each new mint. Pairs with rarityRank to read as \"rank N of M\".
     */
    rarityCategoryTotal?: number | null;
}
export namespace CatDto {
    export const CategoryEnum = {
        Sub1: 'sub1',
        Sub1k: 'sub1k',
        Sub10k: 'sub10k',
        Sub50k: 'sub50k',
        Sub100k: 'sub100k',
        Sub250k: 'sub250k',
        Sub500k: 'sub500k',
        Sub1M: 'sub1M',
        Empty: ''
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
    export const GenderEnum = {
        Female: 'Female',
        Male: 'Male',
        Empty: ''
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
    export const DesignPoseEnum = {
        Standing: 'Standing',
        Sleeping: 'Sleeping',
        Pouncing: 'Pouncing',
        Stalking: 'Stalking'
    } as const;
    export type DesignPoseEnum = typeof DesignPoseEnum[keyof typeof DesignPoseEnum];
    export const DesignExpressionEnum = {
        Smile: 'Smile',
        Grumpy: 'Grumpy',
        Pouting: 'Pouting',
        Shy: 'Shy'
    } as const;
    export type DesignExpressionEnum = typeof DesignExpressionEnum[keyof typeof DesignExpressionEnum];
    export const DesignPatternEnum = {
        Solid: 'Solid',
        Striped: 'Striped',
        Eyepatch: 'Eyepatch',
        HalfHalf: 'Half/Half'
    } as const;
    export type DesignPatternEnum = typeof DesignPatternEnum[keyof typeof DesignPatternEnum];
    export const DesignFacingEnum = {
        Left: 'Left',
        Right: 'Right'
    } as const;
    export type DesignFacingEnum = typeof DesignFacingEnum[keyof typeof DesignFacingEnum];
    export const LaserEyesEnum = {
        Orange: 'Orange',
        Red: 'Red',
        Green: 'Green',
        Blue: 'Blue',
        None: 'None'
    } as const;
    export type LaserEyesEnum = typeof LaserEyesEnum[keyof typeof LaserEyesEnum];
    export const BackgroundEnum = {
        Block9: 'Block9',
        Cyberpunk: 'Cyberpunk',
        Whitepaper: 'Whitepaper',
        Orange: 'Orange'
    } as const;
    export type BackgroundEnum = typeof BackgroundEnum[keyof typeof BackgroundEnum];
    export const CrownEnum = {
        Gold: 'Gold',
        Diamond: 'Diamond',
        None: 'None'
    } as const;
    export type CrownEnum = typeof CrownEnum[keyof typeof CrownEnum];
    export const GlassesEnum = {
        Black: 'Black',
        Cool: 'Cool',
        _3D: '3D',
        Nouns: 'Nouns',
        None: 'None'
    } as const;
    export type GlassesEnum = typeof GlassesEnum[keyof typeof GlassesEnum];
}


