/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatNumbersPaginatedResultDto { 
    /**
     * Array of cat numbers for the current page
     */
    catNumbers: Array<number>;
    /**
     * Total number of cats across all pages
     */
    total: number;
    /**
     * Current page number (1-based)
     */
    currentPage: number;
    /**
     * Number of cats per page
     */
    itemsPerPage: number;
}

