/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatDto } from './catDto';


export interface CatsPaginatedResultDto { 
    cats: Array<CatDto>;
    total: number;
    currentPage: number;
    itemsPerPage: number;
}

