/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatabaseHealthDto { 
    /**
     * Whether the database responded to a SELECT 1 ping
     */
    reachable: boolean;
    /**
     * DB round-trip time in ms for the SELECT 1 ping. Null when the ping failed.
     */
    latencyMs: number | null;
    /**
     * Short error message from the database driver when unreachable (truncated to 200 chars). Null when reachable.
     */
    error: string | null;
}

