/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseHealthDto } from './databaseHealthDto';
import { CacheStatsDto } from './cacheStatsDto';
import { SyncHealthDto } from './syncHealthDto';


export interface ExtendedHealthDto { 
    /**
     * Rollup status: \"ok\" when DB is reachable and sync is fresh; \"degraded\" when DB is reachable but sync is stalled; \"down\" when the DB ping failed.
     */
    status: ExtendedHealthDto.StatusEnum;
    /**
     * Current server time (ISO 8601)
     */
    timestamp: string;
    /**
     * Server uptime in seconds
     */
    uptimeSec: number;
    /**
     * Backend version
     */
    version: string;
    /**
     * Resident memory in MB
     */
    memoryMB: number;
    /**
     * Result of a live SELECT 1 against the database
     */
    database: DatabaseHealthDto;
    /**
     * Last sync cycle outcome and freshness signal
     */
    sync: SyncHealthDto;
    /**
     * In-memory cache statistics
     */
    cache: CacheStatsDto;
}
export namespace ExtendedHealthDto {
    export const StatusEnum = {
        Ok: 'ok',
        Degraded: 'degraded',
        Down: 'down'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


