/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HealthDto { 
    status: string;
    timestamp: string;
    uptimeSec: number;
    version: string;
}

