/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HealthDto { 
    /**
     * Service status
     */
    status: string;
    /**
     * Current server time (ISO 8601)
     */
    timestamp: string;
    /**
     * Server uptime in seconds
     */
    uptimeSec: number;
    /**
     * Backend version
     */
    version: string;
}

