/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MintTransactionEntity { 
    transactionId: string;
    network: string;
    transactionHex: string;
    paymentAddress: string;
    recipientAddress: string;
    createdAt: string;
}

