/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MintTransaction { 
    /**
     * The transaction ID that minted the cat.
     */
    transactionId: string;
    /**
     * The bitcoin network that was used to mint. Possible values: \"mainnet\" or \"testnet\"
     */
    network: string;
    /**
     * The full signed transaction in hex encoded format, so that we can verify that the txn is valid.
     */
    transactionHex: string;
    /**
     * The address that funded the transaction (address of the input).
     */
    paymentAddress: string;
    /**
     * The address that received the cat (address of the first output).
     */
    recipientAddress: string;
    /**
     * ISO formatted string with the exact time when the transaction was signed.
     */
    createdAt: string;
}

