/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusDto { 
    /**
     * Total number of indexed cats
     */
    totalCats: number;
    /**
     * Cat number of the last synced cat (-1 if none)
     */
    lastSyncedCatNumber: number;
}

