/**
 * CAT-21 Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SyncHealthDto { 
    /**
     * ISO timestamp of the last successful sync cycle. Null until the first cycle completes after startup.
     */
    lastSuccessAt: string | null;
    /**
     * ISO timestamp of the last sync cycle that threw. Null when no sync has errored since startup.
     */
    lastErrorAt: string | null;
    /**
     * Short message of the last sync error. Null when no sync has errored since startup.
     */
    lastError: string | null;
    /**
     * Seconds since the last successful sync cycle. Null until the first successful cycle.
     */
    secondsSinceLastSuccess: number | null;
    /**
     * True when the sync has not succeeded within the stall threshold (default 300 s).
     */
    stalled: boolean;
}

