/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhitelistStatusResult { 
    /**
     * The address of this status result.
     */
    walletAddress: string;
    /**
     * The whitelist level: Airdrop, Premint, or Public
     */
    level: string;
    /**
     * If this returns `false`, then do not allow minting. If this returns `true` then 😻😻😻!
     */
    mintingAllowed: boolean;
    /**
     * ISO formated string with the exact time when the address is allowed to mint.
     */
    mintingAllowedAt: string;
}

