/**
 * 🐱 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cat21SingleResultCat } from './cat21SingleResultCat';


export interface Cat21SingleResult { 
    cat: Cat21SingleResultCat;
    /**
     * Previous cat\'s transactionId OR NULL
     */
    previousTransactionId: string;
    /**
     * Next cat\'s transactionId OR NULL
     */
    nextTransactionId: string;
}

