/**
 * 🐱 CAT-21 Indexer API
 * Meow! Don\'t eat cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Cat21 { 
    /**
     * The transactionId where the CAT-21 asset was created / minted
     */
    transactionId: string;
    /**
     * The incremented number of the cat. Cat 0 is the first one.
     */
    number: number;
    /**
     * The block height where the CAT-21 asset was created / minted
     */
    blockHeight: number;
    /**
     * Total fees paid to process the mint transaction in (Unit: sats)
     */
    fee: number;
    /**
     * Total size of the mint transaction (Unit: Bytes)
     */
    size: number;
    /**
     * Weight of the mint transaction, which is a measurement to compare the size of different transactions to each other in proportion to the block size limit (Unit: WU)
     */
    weight: number;
}

