/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cat21 } from './cat21';


export interface Cat21PaginatedResult { 
    /**
     * An array of CAT-21 assets
     */
    cats: Array<Cat21>;
    /**
     * Total number of all CAT-21 assets
     */
    totalResults: number;
    itemsPerPage: number;
    currentPage: number;
}

