/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse {
    /**
     * The HTTP status code
     */
    statusCode: number;
    /**
     * ISO formated string with the exact moment when the error was fetched
     */
    timestamp: string;
    /**
     * Exact path that was called
     */
    path: string;
    /**
     * Explanation of the issue
     */
    message: string;
    /**
     * Optional stack trace
     */
    stack: string | null;
}

