/**
 * 🟧 CAT-21 Indexer API
 * Meow! Rescue the cats!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusResult { 
    /**
     * The network of this status response (mainnet or testnet).
     */
    network: string;
    /**
     * Total number of all indexed CAT-21 ordinals.
     */
    indexedCats: number;
    /**
     * ISO formated string with the time of the last execution of the indexer.
     */
    lastSuccessfulExecution: string;
    /**
     * The number of seconds the server process has been running.
     */
    uptime: number;
}

